### ISSUE TITLE
技術質問

### ISSUE THREAD

**Issue by nakatatsu77** [nakatatsu77/JobFailsDiary#76]
## 解決したいこと・達成したいものについて
Open AIのAPIを使用して、画像生成機能を、私のアプリの投稿機能に組み込みたいです。
#### 現在の投稿機能として以下の２つの機能があります。
- ユーザーが自分で画像を選んで投稿する
- 画像なしで投稿をした場合はデフォルト画像が表示される

こちらの投稿機能に新たに、「body（prompt）の内容から画像を生成して表示する」といった機能を実装したいと考えております。

## 聞きたいこと・アドバイスが欲しいこと
生成画像を表示できるようにするために、(app/controllers/posts_controller.rb)、(app/views/posts/new.html.erb)、(app/views/posts/show.html.erb)の３つを編集し、投稿を行なってみましたが、投稿は作成されておらず、openai apiを使用するためのクレジットだけが消費されておりました。
その際、ログには以下のように表示されておりました。
```
web-1  | 00:43:43 web.1  | Started GET "/manifest.json" for 192.168.65.1 at 2024-12-18 00:43:43 +0900
web-1  | 00:43:43 web.1  | Cannot render console from 192.168.65.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web-1  | 00:43:43 web.1  | Processing by Rails::PwaController#manifest as JSON
web-1  | 00:43:43 web.1  |   Rendering pwa/manifest.json.erb
web-1  | 00:43:43 web.1  |   Rendered pwa/manifest.json.erb (Duration: 2.6ms | GC: 0.0ms)
web-1  | 00:43:43 web.1  | Completed 200 OK in 20ms (Views: 10.4ms | ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)
web-1  | 00:43:43 web.1  | 
web-1  | 00:43:43 web.1  | 
web-1  | 00:43:51 web.1  | Started POST "/posts" for 192.168.65.1 at 2024-12-18 00:43:51 +0900
web-1  | 00:43:51 web.1  | Cannot render console from 192.168.65.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web-1  | 00:43:51 web.1  | Processing by PostsController#create as TURBO_STREAM
web-1  | 00:43:51 web.1  |   Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"prompt"=>"犬の画像"}, "commit"=>"投稿する"}
web-1  | 00:43:51 web.1  |   User Load (1.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
web-1  | 00:43:51 web.1  | Unpermitted parameter: :prompt. Context: { controller: PostsController, action: create, request: #<ActionDispatch::Request:0x0000ffff82049070>, params: {"authenticity_token"=>"[FILTERED]", "post"=>{"prompt"=>"犬の画像"}, "commit"=>"投稿する", "controller"=>"posts", "action"=>"create"} }
web-1  | 00:44:09 web.1  | Post Errors: ["Body can't be blank"]
web-1  | 00:44:09 web.1  |   Rendering layout layouts/application.html.erb
web-1  | 00:44:09 web.1  |   Rendering posts/new.html.erb within layouts/application
web-1  | 00:44:09 web.1  |   Rendered posts/new.html.erb within layouts/application (Duration: 10.6ms | GC: 4.0ms)
web-1  | 00:44:09 web.1  |   Rendered shared/_header.html.erb (Duration: 8.2ms | GC: 0.0ms)
web-1  | 00:44:09 web.1  |   Rendered shared/_footer.html.erb (Duration: 0.1ms | GC: 0.0ms)
web-1  | 00:44:09 web.1  |   Rendered layout layouts/application.html.erb (Duration: 38.1ms | GC: 4.0ms)
web-1  | 00:44:09 web.1  | Completed 422 Unprocessable Content in 17896ms (Views: 44.4ms | ActiveRecord: 1.6ms (1 query, 0 cached) | GC: 6.9ms)
web-
```
どの部分が誤りなのかをご教示いただきたいです。

画像生成自体がちゃんとできるのか確認するためにQiitaの記事を参考に、(images_controller.rb)、(app/views/images/index.html.erb)を作成して、実装をしたところimages配下のビューでは問題なく画像を生成して表示することができました。[qiita記事2](https://qiita.com/Kazukiya/items/9183e6959166c3eb5990)

### 参考資料
[ruby-openai](https://github.com/alexrudall/ruby-openai)
[openaiドキュメント](https://platform.openai.com/docs/guides/images)
[qiita記事1](https://qiita.com/yocaji/items/cbce3cb92c601984314c)
[qiita記事2](https://qiita.com/Kazukiya/items/9183e6959166c3eb5990)

## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
[プルリクエスト](https://github.com/nakatatsu77/portfolio/pull/75)

## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
PostsController#createアクションでpromptの取得部分が関係していると考えております。

## 検証した結果から分かったこと・考えたこと
promptの内容が取得できていない？と考えております。

**Comment by kenchasonakai** [comment]
> PostsController#createアクションでpromptの取得部分が関係していると考えております。
> promptの内容が取得できていない？と考えております。

記載していただいた内容からparamsにpromptが含まれていないこと・post_paramsでpromptが取得されていないことが本当にそうなのかどうかを判断することが出来ませんでしたのでまずはこの推測・疑問が本当にあっているのかどうかを検証するとよいと思います。

検証方法として考えられるのは
1. Loggerを使用してログにparamsやpost_paramsを出力する方法
2. デバッグツールを使用して処理と途中で止めて自分でparamsやpost_params、`@post`などを実行することで返り値が何になっているか確認する

上記2つがさっと出てきますのでやってみてください
2に関しては下記の記事等が少し参考になるかと思います。
https://qiita.com/ruti-cat51/items/fde58bf29273cc5de851
https://techtechmedia.com/pry-rails-docker/

**Comment by nakatatsu77** [comment]
> 記載していただいた内容からparamsにpromptが含まれていないこと・post_paramsでpromptが取得されていないことが本当にそうなのかどうかを判断することが出来ませんでしたのでまずはこの推測・疑問が本当にあっているのかどうかを検証するとよいと思います。

Loggerを使用してログにparamsやpost_paramsを出力する方法を試してみた結果、promptの内容は取得できているようでした。
image_urlがnilになっていたため、こちらがうまく保存できていないのが原因だと考えておりますが、解決方法がわからないためご教示いただきたいです。


以下投稿した時のログになります。
```
Started POST "/posts" for 192.168.65.1 at 2024-12-20 14:18:27 +0900
Cannot render console from 192.168.65.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by PostsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"body"=>"猫の画像"}, "commit"=>"投稿する"}
  User Load (10.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Full Params: #<ActionController::Parameters {"authenticity_token"=>"rhc6foEaWemYe8ND09xAPTokWGudgZmeZ_D0yQYp1BzcN_CWqDvHTfWTSUDFcDI7tfdMbgbMUD1q2uEv0iwk4w", "post"=>{"body"=>"猫の画像"}, "commit"=>"投稿する", "controller"=>"posts", "action"=>"create"} permitted: false>
Filtered Post Params: #<ActionController::Parameters {"body"=>"猫の画像"} permitted: true>
  TRANSACTION (10.2ms)  BEGIN
  ↳ app/controllers/posts_controller.rb:51:in `create'
  Post Create (50.3ms)  INSERT INTO "posts" ("body", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["body", "猫の画像"], ["user_id", 1], ["created_at", "2024-12-20 05:18:37.808365"], ["updated_at", "2024-12-20 05:18:37.808365"]]
  ↳ app/controllers/posts_controller.rb:51:in `create'
  Image Create (2.5ms)  INSERT INTO "images" ("image_url", "is_generated_by_ai", "user_id", "post_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["image_url", nil], ["is_generated_by_ai", false], ["user_id", 1], ["post_id", 17], ["created_at", "2024-12-20 05:18:37.877879"], ["updated_at", "2024-12-20 05:18:37.877879"]]
  ↳ app/controllers/posts_controller.rb:51:in `create'
  TRANSACTION (3.5ms)  COMMIT
  ↳ app/controllers/posts_controller.rb:51:in `create'
Redirected to http://localhost:3000/posts
Completed 302 Found in 10523ms (ActiveRecord: 77.0ms (3 queries, 0 cached) | GC: 76.4ms)


Started GET "/posts" for 192.168.65.1 at 2024-12-20 14:18:37 +0900
Cannot render console from 192.168.65.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by PostsController#index as TURBO_STREAM
  User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Rendering layout layouts/application.html.erb
  Rendering posts/index.html.erb within layouts/application
  Post Load (0.5ms)  SELECT "posts".* FROM "posts"
  ↳ app/views/posts/index.html.erb:11
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1  [["id", 1]]
  ↳ app/views/posts/index.html.erb:11
  Image Load (0.4ms)  SELECT "images".* FROM "images" WHERE "images"."post_id" = $1 LIMIT $2  [["post_id", 1], ["LIMIT", 1]]
  ↳ app/views/posts/_post.html.erb:7
  Image Load (0.2ms)  SELECT "images".* FROM "images" WHERE "images"."post_id" = $1 LIMIT $2  [["post_id", 2], ["LIMIT", 1]]
  ↳ app/views/posts/_post.html.erb:7
  Image Load (0.3ms)  SELECT "images".* FROM "images" WHERE "images"."post_id" = $1 LIMIT $2  [["post_id", 3], ["LIMIT", 1]]
  ↳ app/views/posts/_post.html.erb:7
  Image Load (0.5ms)  SELECT "images".* FROM "images" WHERE "images"."post_id" = $1 LIMIT $2  [["post_id", 11], ["LIMIT", 1]]
  ↳ app/views/posts/_post.html.erb:7
  Image Load (0.3ms)  SELECT "images".* FROM "images" WHERE "images"."post_id" = $1 LIMIT $2  [["post_id", 12], ["LIMIT", 1]]
  ↳ app/views/posts/_post.html.erb:7
  Image Load (0.9ms)  SELECT "images".* FROM "images" WHERE "images"."post_id" = $1 LIMIT $2  [["post_id", 13], ["LIMIT", 1]]
  ↳ app/views/posts/_post.html.erb:7
  Image Load (0.3ms)  SELECT "images".* FROM "images" WHERE "images"."post_id" = $1 LIMIT $2  [["post_id", 14], ["LIMIT", 1]]
  ↳ app/views/posts/_post.html.erb:7
  Image Load (0.1ms)  SELECT "images".* FROM "images" WHERE "images"."post_id" = $1 LIMIT $2  [["post_id", 15], ["LIMIT", 1]]
  ↳ app/views/posts/_post.html.erb:7
  Image Load (0.1ms)  SELECT "images".* FROM "images" WHERE "images"."post_id" = $1 LIMIT $2  [["post_id", 16], ["LIMIT", 1]]
  ↳ app/views/posts/_post.html.erb:7
  Image Load (0.1ms)  SELECT "images".* FROM "images" WHERE "images"."post_id" = $1 LIMIT $2  [["post_id", 17], ["LIMIT", 1]]
  ↳ app/views/posts/_post.html.erb:7
  Rendered collection of posts/_post.html.erb [10 times] (Duration: 50.3ms | GC: 17.9ms)
  Rendered posts/index.html.erb within layouts/application (Duration: 61.5ms | GC: 19.5ms)
  Rendered shared/_header.html.erb (Duration: 1.2ms | GC: 0.0ms)
  Rendered shared/_footer.html.erb (Duration: 0.0ms | GC: 0.0ms)
  Rendered layout layouts/application.html.erb (Duration: 67.8ms | GC: 19.5ms)
Completed 200 OK in 74ms (Views: 64.8ms | ActiveRecord: 4.4ms (13 queries, 0 cached) | GC: 21.4ms)

```

**Comment by nakatatsu77** [comment]
> responseの中身は確認しましたか？
if response.key?("data")とされていますが、条件分岐はどちらが動いているか確認しましたか？

以下実行結果のログになります。
```
Started POST "/posts" for 192.168.65.1 at 2024-12-20 16:38:33 +0900
Cannot render console from 192.168.65.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by PostsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "post"=>{"body"=>"三毛猫の画像"}, "commit"=>"投稿する"}
  User Load (14.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Full Params: #<ActionController::Parameters {"authenticity_token"=>"1dXRIlxfU6gVFoQuxKcT_1j5UgBGbfKychuBW5-6Jkyn9RvKdX7NDHj-Di3SC2H51ypGBd0gOxF_MZS9S7_Wsw", "post"=>{"body"=>"三毛猫の画像"}, "commit"=>"投稿する", "controller"=>"posts", "action"=>"create"} permitted: false>
OpenAI Response: {"created"=>1734680325, "data"=>[{"revised_prompt"=>"A detailed illustration of a tricolor cat, sitting with its tail curled around its body. The cat has patterns of black, white, and orange fur. Its eyes are bright yellow, and it looks directly at the viewer with a calm, curious gaze.", "url"=>"https://oaidalleapiprodscus.blob.core.windows.net/private/org-JKTJ8d9cpt8q0BzpgY0E4rO2/user-IJ7fxdQBR6r5cvj71olCtsny/img-Rj7O73ytRxdzbD1NBtCJQG7s.png?st=2024-12-20T06%3A38%3A45Z&se=2024-12-20T08%3A38%3A45Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-12-20T00%3A29%3A00Z&ske=2024-12-21T00%3A29%3A00Z&sks=b&skv=2024-08-04&sig=ZJPwGYCQrUi0V7Dk/sBU%2BBVi5T09qEFMbvKGWf3nU3Q%3D"}]}
Response contains 'data' key.
Extracted Image URL: https://oaidalleapiprodscus.blob.core.windows.net/private/org-JKTJ8d9cpt8q0BzpgY0E4rO2/user-IJ7fxdQBR6r5cvj71olCtsny/img-Rj7O73ytRxdzbD1NBtCJQG7s.png?st=2024-12-20T06%3A38%3A45Z&se=2024-12-20T08%3A38%3A45Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-12-20T00%3A29%3A00Z&ske=2024-12-21T00%3A29%3A00Z&sks=b&skv=2024-08-04&sig=ZJPwGYCQrUi0V7Dk/sBU%2BBVi5T09qEFMbvKGWf3nU3Q%3D
Building image with URL: https://oaidalleapiprodscus.blob.core.windows.net/private/org-JKTJ8d9cpt8q0BzpgY0E4rO2/user-IJ7fxdQBR6r5cvj71olCtsny/img-Rj7O73ytRxdzbD1NBtCJQG7s.png?st=2024-12-20T06%3A38%3A45Z&se=2024-12-20T08%3A38%3A45Z&sp=r&sv=2024-08-04&sr=b&rscd=inline&rsct=image/png&skoid=d505667d-d6c1-4a0a-bac7-5c84a87759f8&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-12-20T00%3A29%3A00Z&ske=2024-12-21T00%3A29%3A00Z&sks=b&skv=2024-08-04&sig=ZJPwGYCQrUi0V7Dk/sBU%2BBVi5T09qEFMbvKGWf3nU3Q%3D
Before Save - Image Attributes: {"id"=>nil, "image_url"=>nil, "is_generated_by_ai"=>false, "user_id"=>1, "post_id"=>nil, "created_at"=>nil, "updated_at"=>nil}
Filtered Post Params: #<ActionController::Parameters {"body"=>"三毛猫の画像"} permitted: true>
Post Before Save: #<Post id: nil, body: "三毛猫の画像", user_id: 1, created_at: nil, updated_at: nil>
```
